WebApp/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models;

public class LoginViewModel
{
    [Required(ErrorMessage = "Invalid email")]
    [DataType(DataType.EmailAddress)]
    [Display(Name = "Email", Prompt = "Enter email")]

    public string Email { get; set; } = null!;

    [Required (ErrorMessage = "Invalid password")]
    [DataType(DataType.Password)]
    [Display(Name = "Password", Prompt = "Enter password")]

    public string Password { get; set; } = null!;

    public bool RememberMe { get; set; }

    public string? ReturnUrl { get; set; }
}

WebApp/Controllers/LogInController.cs
using Business.Services;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class LogInController : Controller
    {
        private readonly IAuthService _authService;

        public LogInController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Index(string returnUrl = "/")
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            ViewBag.ReturnUrl = model.ReturnUrl;

            if (!ModelState.IsValid)
                return View(model);

            var formData = new SignInFormData
            {
                Email = model.Email,
                Password = model.Password,
                IsPersistent = model.RememberMe
            };

            var result = await _authService.SignInAsync(formData);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Projects");
            }

            ViewBag.ErrorMessage = result.Error;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _authService.SignOutAsync();
            return RedirectToAction("Index", "LogIn");
        }
    }
}

WebApp/Controllers/SignUpController.cs
using Business.Services;
using Domain.Extentions;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SignUpController : Controller
    {
        private readonly IAuthService _authService;

        public SignUpController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(SignUpViewModel model)
        {
            ViewBag.ErrorMessage = null;

            if (!ModelState.IsValid)
                return View(model);

            var signUpFormData = model.MapTo<SignUpFormData>();

            var result = await _authService.SignUpAsync(signUpFormData);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "LogIn");
            }

            ViewBag.ErrorMessage = result.Error;
            return View(model);
        }
    }
}

WebApp/Views/LogIn/Index.cshtml
@model LoginViewModel

@{
	Layout = "_CenterWrapperLayout";
	ViewData["Title"] = "Login";
}

<section id="login">
    <div class="card">
        <div class="card-header">
            <h1>@ViewData["Title"]</h1>
        </div>
        <div class="card-body">
            <form method="post" asp-controller="Login" asp-action="ExternalLogin" novalidate>
                <button type="submit" class="btn-external">
                    <img src="/images/icons/google-icon.svg">
                    <span>Log in with Google</span>
                </button>
            </form>

            <div class="divider">
                <span>or</span>
            </div>

            <form method="post" asp-controller="Login" asp-action="Index" novalidate>
                @Html.AntiForgeryToken()
                <input type="hidden" asp-for="ReturnUrl" />

                <div class="form-group">
                    <label class="form-label" asp-for="Email"></label>
                    <input class="form-input" asp-for="Email" />
                    <span asp-validation-for="Email"></span>
                </div>
                <div class="form-group">
                    <label class="form-label" asp-for="Password"></label>
                    <input class="form-input" asp-for="Password" />
                    <span asp-validation-for="Password"></span>
                </div>
                <div class="form-checkbox-group">
                    <label class="form-checkbox">
                        <input asp-for="RememberMe" class="form-checkbox-input" />
                        <span class="form-checkbox-box"></span>
                    </label>
                    <label asp-for="RememberMe" class="form-label"></label>
                </div>
                <button type="submit" class="btn btn-blue">Log In</button>
            </form>
        </div>
        <div class="card-footer">Don't have an account? <a asp-controller="SignUp" asp-action="Index">Sign Up</a></div>
    </div>
</section>